plugins {
    id 'java'
    id 'application'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}


dependencies {
    testImplementation 'org.apache.commons:commons-lang3:3.12.0'
    testImplementation 'com.github.javaparser:javaparser-symbol-solver-core:3.24.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    
    // Add dependencies for the main application
    implementation 'com.github.javaparser:javaparser-symbol-solver-core:3.24.2'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'TestRunner'
}

task runAnalysis(type: JavaExec) {
    dependsOn 'compileTestJava'
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'TestRunner'
}